blockargs = {
    "motion": {
        "motion_movesteps": [["steps"], []],
        "motion_turnright": [["degrees"], []],
        "motion_turnleft": [["degrees"], []],
        "motion_goto": [["to"], []],
        "motion_gotoxy": [["x", "y"], []],
        "motion_glideto": [["secs", "to"], []],
        "motion_glidesecstoxy": [["secs", "x", "y"], []],
        "motion_pointindirection": [["direction"], []],
        "motion_pointtowards": [["towards"], []],
        "motion_changexby": [["dx"], []],
        "motion_changeyby": [["dy"], []],
        "motion_setx": [["x"], []],
        "motion_sety": [["y"], []],
        "motion_ifonedgebounce": [[], []],
        "motion_setrotationstyle": [["style"], []],
        "motion_xposition": [[], []],
        "motion_yposition": [[], []],
        "motion_direction": [[], []],
    },
    "looks": {
        "looks_sayforsecs": [["MESSAGE", "SECS"], []],
        "looks_say": [["MESSAGE"], []],
        "looks_thinkforsecs": [["MESSAGE", "SECS"], []],
        "looks_think": [["MESSAGE"], []],
        "looks_switchcostumeto": [["COSTUME"], []],
        "looks_nextcostume": [[], []],
        "looks_switchbackdropto": [["BACKDROP"], []],
        "looks_switchbackdroptoandwait": [["BACKDROP"], []],
        "looks_nextbackdrop": [[], []],
        "looks_changesizeby": [["CHANGE"], []],
        "looks_setsizeto": [["SIZE"], []],
        "looks_changeeffectby": [["CHANGE"], ["EFFECT"]],
        "looks_seteffectto": [["VALUE"], ["EFFECT"]],
        "looks_cleargraphiceffects": [[], []],
        "looks_show": [[], []],
        "looks_hide": [[], []],
        "looks_gotofrontback": [[], ["FRONT_BACK"]],
        "looks_goforwardbackwardlayers": [["NUM"], ["FORWARD_BACKWARD"]],
        "looks_costumenumbername": [[], ["NUMBER_NAME"]],
        "looks_backdropnumbername": [[], ["NUMBER_NAME"]],
        "looks_size": [[], []],
    },
    "sound": {
        "sound_playuntildone": [["SOUND_MENU"], []],
        "sound_play": [["SOUND_MENU"], []],
        "sound_stopallsounds": [[], []],
        "sound_changeeffectby": [["VALUE"], ["EFFECT"]],
        "sound_seteffectto": [["VALUE"], ["EFFECT"]],
        "sound_cleareffects": [[], []],
        "sound_changevolumeby": [["VOLUME"], []],
        "sound_setvolumeto": [["VOLUME"], []],
        "sound_volume": [[], []],
    },
    "event": {
        "event_whenflagclicked": [[], []],
        "event_whenkeypressed": [["KEY_OPTION"], []],
        "event_whenthisspriteclicked": [[], []],
        "event_whenstageclicked": [[], []],
        "event_whenbackdropswitchesto": [[], ["BACKDROP"]],
        "event_whengreaterthan": [["VALUE"], ["WHENGREATERTHANMENU"]],
        "event_whenbroadcastreceived": [[], ["BROADCAST_OPTION"]],
        "event_broadcast": [["BROADCAST_INPUT"], []],
        "event_broadcastandwait": [["BROADCAST_INPUT"], []],
        "event_whentouchingobject": [["WHENTOUCHINGOBJECTMENU"], []],
    },
    "control": {
        "control_wait": [["DURATION"], []],
        "control_repeat": [["TIMES", "SUBSTACK"], []],
        "control_forever": [["SUBSTACK"], []],
        "control_if": [["CONDITION", "SUBSTACK"], []],
        "control_if_else": [["CONDITION", "SUBSTACK", "SUBSTACK2"], []],
        "control_wait_until": [["CONDITION"], []],
        "control_repeat_until": [["CONDITION", "SUBSTACK"], []],
        "control_stop": [["STOP_OPTION"], []],
        "control_start_as_clone": [[], []],
        "control_create_clone_of": [["CLONE_OPTION"], []],
        "control_delete_this_clone": [[], []],
        "control_for_each": [["VALUE", "SUBSTACK"], ["VARIABLE"]],
        "control_while": [["CONDITION", "SUBSTACK"], []],
        "control_get_counter": [[], []],
        "control_incr_counter": [[], []],
        "control_clear_counter": [[], []],
        "control_all_at_once": [[], []],
    },
    "sensing": {
        "sensing_touchingobject": [["TOUCHINGOBJECTMENU"], []],
        "sensing_touchingcolor": [["COLOR"], []],
        "sensing_coloristouchingcolor": [["COLOR", "COLOR2"], []],
        "sensing_distanceto": [["DISTANCETOMENU"], []],
        "sensing_askandwait": [["QUESTION"], []],
        "sensing_answer": [[], []],
        "sensing_keypressed": [["KEY_OPTION"], []],
        "sensing_mousedown": [[], []],
        "sensing_mousex": [[], []],
        "sensing_mousey": [[], []],
        "sensing_setdragmode": [["DRAG_MODE"], []],
        "sensing_loudness": [[], []],
        "sensing_timer": [[], []],
        "sensing_resettimer": [[], []],
        "sensing_of": [["PROPERTY", "OBJECT"], []],
        "sensing_current": [[], ["CURRENTMENU"]],
        "sensing_dayssince2000": [[], []],
        "sensing_username": [[], []],
    },
    "operator": {
        "operator_random": [["FROM", "TO"], []],
        "operator_add": [["NUM1", "NUM2"], []],
        "operator_subtract": [["NUM1", "NUM2"], []],
        "operator_multiply": [["NUM1", "NUM2"], []],
        "operator_divide": [["NUM1", "NUM2"], []],
        "operator_gt": [["OPERAND1", "OPERAND2"], []],
        "operator_lt": [["OPERAND1", "OPERAND2"], []],
        "operator_equals": [["OPERAND1", "OPERAND2"], []],
        "operator_and": [["OPERAND1", "OPERAND2"], []],
        "operator_or": [["OPERAND1", "OPERAND2"], []],
        "operator_not": [["OPERAND"], []],
        "operator_join": [["STRING1", "STRING2"], []],
        "operator_letter_of": [["LETTER", "STRING"], []],
        "operator_length": [["STRING"], []],
        "operator_contains": [["STRING1", "STRING2"], []],
        "operator_mod": [["STRING1", "STRING2"], []],
        "operator_round": [["NUM"], []],
        "operator_mathop": [["NUM"], ["OPERATOR"]],
    },
    "data": {
        "data_setvariableto": [["VALUE"], ["VARIABLE"]],
        "data_changevariableby": [["VALUE"], ["VARIABLE"]],
        "data_showvariable": [[], ["VARIABLE"]],
        "data_hidevariable": [[], ["VARIABLE"]],
        "data_addtolist": [["ITEM"], ["LIST"]],
        "data_deleteoflist": [["INDEX"], ["LIST"]],
        "data_deletealloflist": [[], ["LIST"]],
        "data_insertatlist": [["ITEM", "INDEX"], ["LIST"]],
        "data_replaceitemoflist": [["INDEX", "ITEM"], ["LIST"]],
        "data_itemoflist": [["INDEX"], ["LIST"]],
        "data_itemnumoflist": [["ITEM"], ["LIST"]],
        "data_lengthoflist": [[], ["LIST"]],
        "data_listcontainsitem": [["ITEM"], ["LIST"]],
        "data_showlist": [[], ["LIST"]],
        "data_hidelist": [[], ["LIST"]],
    },
}
